//Deobfuscated with https://github.com/SimplyProgrammer/Minecraft-Deobfuscator3000 using mappings "C:\Users\38096\Downloads\Minecraft-Deobfuscator3000-master\1.12 stable mappings"!

//Decompiled by Procyon!

package net.labymod.main;

public class ModTextures
{
    public static final String TEXTURE_FOLDER = "labymod/textures/";
    public static final String SETTING = "labymod/textures/settings/";
    public static final String SETTING_GUI_CATEGORY_ICONS = "labymod/textures/settings/guicategory/";
    public static final String SETTING_CATEGORY_ICONS = "labymod/textures/settings/category/";
    public static final String SETTING_ICONS = "labymod/textures/settings/settings/";
    public static final String TABS = "labymod/textures/settings/tabs/";
    public static final String MODULE_ICONS = "labymod/textures/settings/modules/";
    public static final String SKIN_ICONS = "labymod/textures/settings/skin/";
    public static final String COSMETICS = "labymod/textures/cosmetics/";
    public static final String PETS = "labymod/textures/cosmetics/pets/";
    public static final String CHAT = "labymod/textures/chat/";
    public static final String MISC = "labymod/textures/misc/";
    public static final String BUTTONS = "labymod/textures/buttons/";
    public static final String BADGES = "labymod/textures/badges/";
    public static final String LANGUAGE_FLAGS = "labymod/textures/flags/%s.png";
    public static final nf SETTINGS_MODULE_EDITOR_BG;
    public static final nf SETTINGS_DEFAULT_USE_DEFAULT_SETTINGS;
    public static final nf SETTINGS_DEFAULT_DISPLAY_KEY;
    public static final nf SETTINGS_DEFAULT_GRID_MOVEMENT;
    public static final nf SETTINGS_DEFAULT_ITEM_GRAVITY;
    public static final nf SETTINGS_DEFAULT_GUI_SCALING;
    public static final nf SETTINGS_DEFAULT_BACKGROUND;
    public static final nf SETTINGS_DEFAULT_PADDING;
    public static final nf COSMETIC_CAPE_STAR;
    public static final nf COSMETIC_HALO;
    public static final nf COSMETIC_XMAS;
    public static final nf COSMETIC_CROWN;
    public static final nf COSMETIC_WITCH;
    public static final nf COSMETIC_BLAZE;
    public static final nf COSMETIC_WITHER;
    public static final nf COSMETIC_ENDER_DRAGON_CLASSIC;
    public static final nf COSMETIC_ENDER_DRAGON;
    public static final nf COSMETIC_SNOXH_EYE;
    public static final nf COSMETIC_SNOXH_MASK;
    public static final nf COSMETIC_BANDANA_DEFAULT;
    public static final nf COSMETIC_HEADSET;
    public static final nf COSMETIC_RABBIT;
    public static final nf COSMETIC_TAIL_WOLF;
    public static final nf COSMETIC_TAIL_CAT;
    public static final nf COSMETIC_ANTLER;
    public static final nf COSMETIC_REDNOSE;
    public static final nf COSMETIC_WINGS_STEAMPUNK;
    public static final nf COSMETIC_WINGS_CRYSTAL;
    public static final nf COSMETIC_DEVIL_HORNS;
    public static final nf COSMETIC_BACKPACK;
    public static final nf COSMETIC_REVED_ARM_COLORED;
    public static final nf COSMETIC_REVED_ARM;
    public static final nf COSMETIC_REVED_FLAME;
    public static final nf COSMETIC_ABGEGRIEFT;
    public static final nf COSMETIC_WINGS_CLOUD;
    public static final nf COSMETIC_MASK_FACE;
    public static final nf COSMETIC_EYELIDS;
    public static final nf COSMETIC_EYELIDS_SLEEP;
    public static final nf COSMETIC_WINGS_BUTTERFLY;
    public static final nf COSMETIC_WINGS_BUTTERFLY_OVERLAY;
    public static final nf COSMETIC_WATCH_CASE;
    public static final nf COSMETIC_CAT_TAIL;
    public static final nf COSMETIC_MOOSE_HAT;
    public static final nf COSMETIC_UNICORN_HAT;
    public static final nf COSMETIC_COW_HAT;
    public static final nf COSMETIC_SCARF;
    public static final nf COSMETIC_MUSTACHE;
    public static final nf COSMETIC_PET_QUETZAL;
    public static final nf CHAT_TAB_SYMBOLS;
    public static final nf CHAT_TAB_FILTER;
    public static final nf CHAT_TAB_AUTOTEXT;
    public static final nf CHAT_TAB_SHORTCUT;
    public static final nf CHAT_TAB_PLAYERMENU;
    public static final nf CHAT_TAB_GUI_EDITOR;
    public static final nf BADGE_GROUP;
    public static final nf BADGE_FAMILIAR;
    public static final nf BADGE_GROUP_SMALL;
    public static final nf BADGE_FAMILIAR_SMALL;
    public static final nf MISC_HEAD_SKULL;
    public static final nf MISC_HEAD_QUESTION;
    public static final nf MISC_FEATURED;
    public static final nf MISC_CROWN;
    public static final nf MISC_PARTNER_CROWN;
    public static final nf MISC_PARTY;
    public static final nf MISC_MENU_POINT;
    public static final nf MISC_ARROW;
    public static final nf MISC_BLOCKED;
    public static final nf MISC_MOUSE;
    public static final nf MISC_ECONOMY_CASH;
    public static final nf MISC_ECONOMY_BANK;
    public static final nf MISC_MOJANGSTUDIOS;
    public static final nf MISC_MICROSOFT;
    public static final nf MISC_MICROSOFT_STORE;
    public static final nf MISC_JAVA;
    public static final nf MISC_SODIUM;
    public static final nf MISC_GIVE_IT_A_TRY;
    public static final nf MISC_MARKER_CIRCLE;
    public static final nf MISC_LOCK;
    public static final nf GUI_WRAPPER_INVENTORY;
    public static final nf BUTTON_ACCEPT;
    public static final nf BUTTON_DENY;
    public static final nf BUTTON_CHECKBOX;
    public static final nf BUTTON_SIGNSEARCH;
    public static final nf BUTTON_UPDATE;
    public static final nf BUTTON_EXPAND;
    public static final nf BUTTON_EXCLAMATION;
    public static final nf BUTTON_QUESTION;
    public static final nf BUTTON_CUSTOM;
    public static final nf BUTTON_DOWNLOAD;
    public static final nf BUTTON_TRASH;
    public static final nf BUTTON_RESET;
    public static final nf BUTTON_UNDO;
    public static final nf BUTTON_LARGE;
    public static final nf BUTTON_LARGE_PRESSED;
    public static final nf BUTTON_LARGE_DISABLED;
    public static final nf BUTTON_ADDON_SETTINGS;
    public static final nf BUTTON_HOVER_DEFAULT;
    public static final nf BUTTON_ADVANCED;
    public static final nf LOGO_LABYMOD_LOGO;
    public static final nf TAB_MULTIPLAYER;
    public static final nf TAB_ADDONS;
    public static final nf TAB_GUI;
    public static final nf TAB_CHAT;
    public static final nf TITLE_LABYMOD_BANNER_SPLASH;
    public static final nf TITLE_LABYMOD_BANNER_WATERMARK;
    public static final nf TITLE_MOJANG_BANNER;
    public static final nf TITLE_LABYMOD_WHITE_WOLF;
    public static final nf ITEM_ARROW;
    public static final nf ITEM_SWORD;
    public static final nf ITEM_HELMET;
    public static final nf ITEM_CHESTPLATE;
    public static final nf ITEM_LEGGINGS;
    public static final nf ITEM_BOOTS;
    public static final nf ACHIEVEMENT;
    public static final nf VOID;
    public static final nf TRANSPARENT;
    public static final nf LAYER_CROWN;
    
    static {
        SETTINGS_MODULE_EDITOR_BG = new nf("labymod/textures/settings/module_editor_bg.jpg");
        SETTINGS_DEFAULT_USE_DEFAULT_SETTINGS = new nf("labymod/textures/settings/default/use_default_settings.png");
        SETTINGS_DEFAULT_DISPLAY_KEY = new nf("labymod/textures/settings/default/display_key.png");
        SETTINGS_DEFAULT_GRID_MOVEMENT = new nf("labymod/textures/settings/default/grid_movement.png");
        SETTINGS_DEFAULT_ITEM_GRAVITY = new nf("labymod/textures/settings/default/item_gravity.png");
        SETTINGS_DEFAULT_GUI_SCALING = new nf("labymod/textures/settings/default/gui_scaling.png");
        SETTINGS_DEFAULT_BACKGROUND = new nf("labymod/textures/settings/default/background.png");
        SETTINGS_DEFAULT_PADDING = new nf("labymod/textures/settings/default/padding.png");
        COSMETIC_CAPE_STAR = new nf("labymod/textures/cosmetics/star.png");
        COSMETIC_HALO = new nf("labymod/textures/cosmetics/halo.png");
        COSMETIC_XMAS = new nf("labymod/textures/cosmetics/xmas.png");
        COSMETIC_CROWN = new nf("labymod/textures/cosmetics/crown.png");
        COSMETIC_WITCH = new nf("labymod/textures/cosmetics/flags/default.png");
        COSMETIC_BLAZE = new nf("textures/entity/blaze.png");
        COSMETIC_WITHER = new nf("textures/entity/wither/wither.png");
        COSMETIC_ENDER_DRAGON_CLASSIC = new nf("textures/entity/enderdragon/dragon.png");
        COSMETIC_ENDER_DRAGON = new nf("labymod/textures/cosmetics/dragon.png");
        COSMETIC_SNOXH_EYE = new nf("labymod/textures/cosmetics/snoxh/eye.png");
        COSMETIC_SNOXH_MASK = new nf("labymod/textures/cosmetics/snoxh/mask.png");
        COSMETIC_BANDANA_DEFAULT = new nf("labymod/textures/cosmetics/bandana.png");
        COSMETIC_HEADSET = new nf("labymod/textures/cosmetics/headset.png");
        COSMETIC_RABBIT = new nf("labymod/textures/cosmetics/rabbit.png");
        COSMETIC_TAIL_WOLF = new nf("labymod/textures/cosmetics/wolftail.png");
        COSMETIC_TAIL_CAT = new nf("labymod/textures/cosmetics/cattail.png");
        COSMETIC_ANTLER = new nf("labymod/textures/cosmetics/antler.png");
        COSMETIC_REDNOSE = new nf("labymod/textures/cosmetics/rednose.png");
        COSMETIC_WINGS_STEAMPUNK = new nf("labymod/textures/cosmetics/steampunk.png");
        COSMETIC_WINGS_CRYSTAL = new nf("labymod/textures/cosmetics/crystal.png");
        COSMETIC_DEVIL_HORNS = new nf("labymod/textures/cosmetics/devilhorns.png");
        COSMETIC_BACKPACK = new nf("labymod/textures/cosmetics/backpack.png");
        COSMETIC_REVED_ARM_COLORED = new nf("labymod/textures/cosmetics/reved/arm_colored.png");
        COSMETIC_REVED_ARM = new nf("labymod/textures/cosmetics/reved/arm.png");
        COSMETIC_REVED_FLAME = new nf("labymod/textures/cosmetics/reved/flame.png");
        COSMETIC_ABGEGRIEFT = new nf("labymod/textures/cosmetics/abgegrieft.png");
        COSMETIC_WINGS_CLOUD = new nf("labymod/textures/cosmetics/cloudwings.png");
        COSMETIC_MASK_FACE = new nf("labymod/textures/cosmetics/facemask.png");
        COSMETIC_EYELIDS = new nf("labymod/textures/cosmetics/eyelids.png");
        COSMETIC_EYELIDS_SLEEP = new nf("labymod/textures/cosmetics/eyelids_sleep.png");
        COSMETIC_WINGS_BUTTERFLY = new nf("labymod/textures/cosmetics/butterfly.png");
        COSMETIC_WINGS_BUTTERFLY_OVERLAY = new nf("labymod/textures/cosmetics/butterfly_overlay.png");
        COSMETIC_WATCH_CASE = new nf("labymod/textures/cosmetics/watch_case.png");
        COSMETIC_CAT_TAIL = new nf("labymod/textures/cosmetics/cat_tail.png");
        COSMETIC_MOOSE_HAT = new nf("labymod/textures/cosmetics/moose_hat.png");
        COSMETIC_UNICORN_HAT = new nf("labymod/textures/cosmetics/unicorn_hat.png");
        COSMETIC_COW_HAT = new nf("labymod/textures/cosmetics/cow_hat.png");
        COSMETIC_SCARF = new nf("labymod/textures/cosmetics/scarf.png");
        COSMETIC_MUSTACHE = new nf("labymod/textures/cosmetics/mustache.png");
        COSMETIC_PET_QUETZAL = new nf("labymod/textures/cosmetics/pets/quetzal.png");
        CHAT_TAB_SYMBOLS = new nf("labymod/textures/chat/symbols.png");
        CHAT_TAB_FILTER = new nf("labymod/textures/chat/filter.png");
        CHAT_TAB_AUTOTEXT = new nf("labymod/textures/chat/autotext.png");
        CHAT_TAB_SHORTCUT = new nf("labymod/textures/chat/shortcut.png");
        CHAT_TAB_PLAYERMENU = new nf("labymod/textures/chat/playermenu.png");
        CHAT_TAB_GUI_EDITOR = new nf("labymod/textures/chat/gui_editor.png");
        BADGE_GROUP = new nf("labymod/textures/badges/group_badge.png");
        BADGE_FAMILIAR = new nf("labymod/textures/badges/familiar.png");
        BADGE_GROUP_SMALL = new nf("labymod/textures/badges/group_badge_small.png");
        BADGE_FAMILIAR_SMALL = new nf("labymod/textures/badges/familiar_small.png");
        MISC_HEAD_SKULL = new nf("labymod/textures/misc/skull.png");
        MISC_HEAD_QUESTION = new nf("labymod/textures/misc/question.png");
        MISC_FEATURED = new nf("labymod/textures/misc/featured.png");
        MISC_CROWN = new nf("labymod/textures/misc/crown.png");
        MISC_PARTNER_CROWN = new nf("labymod/textures/misc/partner_crown.png");
        MISC_PARTY = new nf("labymod/textures/misc/party.png");
        MISC_MENU_POINT = new nf("labymod/textures/misc/menu_point.png");
        MISC_ARROW = new nf("labymod/textures/misc/arrow.png");
        MISC_BLOCKED = new nf("labymod/textures/misc/blocked.png");
        MISC_MOUSE = new nf("labymod/textures/misc/mouse.png");
        MISC_ECONOMY_CASH = new nf("labymod/textures/misc/economy_cash.png");
        MISC_ECONOMY_BANK = new nf("labymod/textures/misc/economy_bank.png");
        MISC_MOJANGSTUDIOS = new nf("labymod/textures/misc/mojangstudios.png");
        MISC_MICROSOFT = new nf("labymod/textures/misc/microsoft.png");
        MISC_MICROSOFT_STORE = new nf("labymod/textures/misc/microsoft_store.png");
        MISC_JAVA = new nf("labymod/textures/misc/java.png");
        MISC_SODIUM = new nf("labymod/textures/misc/sodium.png");
        MISC_GIVE_IT_A_TRY = new nf("labymod/textures/misc/give_it_a_try.png");
        MISC_MARKER_CIRCLE = new nf("labymod/textures/misc/marker_circle.png");
        MISC_LOCK = new nf("labymod/textures/misc/lock.png");
        GUI_WRAPPER_INVENTORY = new nf("labymod/textures/gui/container/wrapper_container.png");
        BUTTON_ACCEPT = new nf("labymod/textures/buttons/accept.png");
        BUTTON_DENY = new nf("labymod/textures/buttons/deny.png");
        BUTTON_CHECKBOX = new nf("labymod/textures/buttons/checkbox.png");
        BUTTON_SIGNSEARCH = new nf("labymod/textures/buttons/sign_search.png");
        BUTTON_UPDATE = new nf("labymod/textures/buttons/update.png");
        BUTTON_EXPAND = new nf("labymod/textures/buttons/expand.png");
        BUTTON_EXCLAMATION = new nf("labymod/textures/buttons/exclamation_mark.png");
        BUTTON_QUESTION = new nf("labymod/textures/buttons/question_mark.png");
        BUTTON_CUSTOM = new nf("labymod/textures/buttons/button_custom.png");
        BUTTON_DOWNLOAD = new nf("labymod/textures/buttons/download.png");
        BUTTON_TRASH = new nf("labymod/textures/buttons/trash.png");
        BUTTON_RESET = new nf("labymod/textures/buttons/reset.png");
        BUTTON_UNDO = new nf("labymod/textures/buttons/undo.png");
        BUTTON_LARGE = new nf("labymod/textures/buttons/button_large.png");
        BUTTON_LARGE_PRESSED = new nf("labymod/textures/buttons/button_large_pressed.png");
        BUTTON_LARGE_DISABLED = new nf("labymod/textures/buttons/button_large_disabled.png");
        BUTTON_ADDON_SETTINGS = new nf("labymod/textures/buttons/addon_settings.png");
        BUTTON_HOVER_DEFAULT = new nf("labymod/textures/buttons/hover_default.png");
        BUTTON_ADVANCED = new nf("labymod/textures/buttons/advanced.png");
        LOGO_LABYMOD_LOGO = new nf("labymod/textures/labymod_logo.png");
        TAB_MULTIPLAYER = new nf("labymod/textures/settings/tabs/multiplayer.png");
        TAB_ADDONS = new nf("labymod/textures/settings/tabs/addons.png");
        TAB_GUI = new nf("labymod/textures/settings/tabs/gui.png");
        TAB_CHAT = new nf("labymod/textures/settings/tabs/chat.png");
        TITLE_LABYMOD_BANNER_SPLASH = new nf("labymod/textures/title/labymod_banner_splash.png");
        TITLE_LABYMOD_BANNER_WATERMARK = new nf("labymod/textures/title/labymod_banner_watermark.png");
        TITLE_MOJANG_BANNER = new nf("labymod/textures/title/mojang.png");
        TITLE_LABYMOD_WHITE_WOLF = new nf("labymod/textures/title/white_wolf.png");
        ITEM_ARROW = new nf("labymod/textures/items/arrow.png");
        ITEM_SWORD = new nf("labymod/textures/items/sword.png");
        ITEM_HELMET = new nf("labymod/textures/items/helmet.png");
        ITEM_CHESTPLATE = new nf("labymod/textures/items/chestplate.png");
        ITEM_LEGGINGS = new nf("labymod/textures/items/leggings.png");
        ITEM_BOOTS = new nf("labymod/textures/items/boots.png");
        ACHIEVEMENT = new nf("labymod/textures/achievement_background.png");
        VOID = new nf("labymod/textures/void.png");
        TRANSPARENT = new nf("labymod/textures/transparent.png");
        LAYER_CROWN = new nf("labymod/textures/layers/crown.png");
    }
}
